version: "2"
run:
  concurrency: 10
  issues-exit-code: 1
  tests: true
  modules-download-mode: vendor

output:
  sort-order:
    - linter
    - severity
    - file
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - gochecknoglobals
    - goconst
    - interfacebloat
    - ireturn
    - nolintlint
    - paralleltest
    - perfsprint
    - tagalign
    - tagliatelle
    - wrapcheck
    - noinlineerr
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    gocognit:
      min-complexity: 60
    lll:
      line-length: 145
    nestif:
      min-complexity: 20
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - mnd
        path: _test\.go
      - linters:
          - gocritic
        text: 'unnecessaryDefer:'
    paths:
      - third_party$
      - builtin$
      - examples$
severity:
  default: error
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
